name: Deno Deploy

on:
  push:
    branches: [deno]
  workflow_dispatch:

jobs:
  deploy:
    name: Deno Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      - name: pnpm install and build
        run: |
          pnpm install
          pnpm build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: majudhu
          entrypoint: server/entry.mjs
