name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ghpages:
    runs-on: ubuntu-latest
    name: Deploying to GitHub Pages
    permissions:
      pages: write
      id-token: write
    env:
      BASE: ${{ github.event.repository.name }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v7
      - uses: withastro/action@v6
      - id: deployment
        uses: actions/deploy-pages@v5

  surge:
    runs-on: ubuntu-latest
    name: Deploying to surge.sh
    environment:
      name: surge
      url: https://${{ github.actor }}.surge.sh
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        with:
          version: 12.5.1
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: pnpm
      - name: Astro build and Surge deploy
        run: |
          pnpm add -g surge
          pnpm install
          pnpm build
          surge dist ${{ github.actor }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}
